
name: HW 325


on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v3

    - name: Build
      run: gradle build
    
    - name: Test
      run: gradle test
     
    - name: Coverage Verification
      run: gradle jacocoTestCoverageVerification

    - name: Build
      run: gradle build

    - name: Report Code Coverage
      uses: actions/upload-artifact@v2
      with:
        name: code-coverage-report
        path: build/reports
